'use server';
/**
 * @fileOverview AI-powered text analysis to detect AI-generated content.
 *
 * - detectAiContent - A function that analyzes text and returns the probability of it being AI-generated.
 * - DetectAiContentInput - The input type for the detectAiContent function.
 * - DetectAiContentOutput - The return type for the detectAiContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectAiContentInputSchema = z.object({
  text: z.string().describe('The text to be analyzed for AI content probability.'),
});
export type DetectAiContentInput = z.infer<typeof DetectAiContentInputSchema>;

const DetectAiContentOutputSchema = z.object({
  aiProbability: z.number().min(0).max(100).describe('The probability (0-100) that the text was generated by AI.'),
  summary: z.string().describe('A brief summary of the analysis (e.g., "This text is likely human-written.").'),
});
export type DetectAiContentOutput = z.infer<typeof DetectAiContentOutputSchema>;

export async function detectAiContent(
  input: DetectAiContentInput
): Promise<DetectAiContentOutput> {
  return detectAiContentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'detectAiContentPrompt',
  input: {schema: DetectAiContentInputSchema},
  output: {schema: DetectAiContentOutputSchema},
  prompt: `You are an expert in analyzing text to determine its origin (human-written vs. AI-generated). Your task is to analyze the following text and provide a probability score from 0 to 100 indicating how likely it is to be AI-generated. A score of 0 means it is definitely human-written, and 100 means it is definitely AI-generated.

  Also provide a short, one-sentence summary of your findings. For example: "This text is highly likely to be AI-generated." or "This text appears to be human-written."

  Analyze the following text:
  ---
  {{{text}}}
  ---
  `,
});

const detectAiContentFlow = ai.defineFlow(
  {
    name: 'detectAiContentFlow',
    inputSchema: DetectAiContentInputSchema,
    outputSchema: DetectAiContentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
